accessing
initializeToggleButton: aButton
	^ aButton
		label: '';
		icon:
			(BlElement new
				size: 8 @ 8;
				geometry:
					(BlPolygon
						vertices:
							{(0 @ 0).
							(8 @ 0).
							((8 / 2) rounded @ 8)});
				background: Color lightGray;
				margin: (BlInsets left: 6);
				constraintsDo: [ :c | c linear vertical alignCenter ]);
		aptitude: BrGlamorousButtonWithLabelAndIconAptitude;
		yourself